### ISSUE TITLE
Poner estilos de bootstrap a la tabla. 

### ISSUE THREAD

**Issue by lucasalmi** [lucasalmi/TPE-TIO#1]
Crear una tabla con estilos oscuros, utilizando el framework bootstrap.  @juliacosta98

**Comment by juliacosta98** [comment]
ok

**Comment by juliacosta98** [comment]
`<h3>Lista de cervezas</h3>
<table class="table table-dark">
		<thead>
			<tr>
			<th scope="col">{{titulos.name}}</th>
			<th scope="col">{{titulos.description}}</th>
			<th scope="col">{{titulos.price}}</th>
			<th scope="col">{{titulos.imagen}}</th>
			<th scope="col">{{titulos.stock}}</th>
			<th scope="col">{{titulos.carrito}}</th>
			</tr>
		</thead>
		<tbody>
			<tr *ngFor = "let beer of beers" [ngClass] = "{'oferta': beer.ofert, 'agotado': beer.stock <= 0}">
			<th scope="row">{{beer.name}}</th>
			<td>
					<ul>
						<li>{{titulos.alcohol}}: {{beer.alcohol}}</li>
						<li>{{titulos.ibu}}: {{beer.ibu}}</li>
						<li>{{titulos.color}}: {{beer.color}}</li>
						<li>{{titulos.og}}: {{beer.og}}</li>
						<li>{{titulos.amargor}}: {{beer.amargor}}</li>
					</ul>
				</td>
				<td>{{beer.price | currency}}</td>
				<td><img [src]=beer.imagen [alt]=beer.name width="30%"></td>
				<td><span *ngIf = "beer.stock <= 0"> Agotado </span>
					<span *ngIf = "beer.stock > 0"> Disponible ({{beer.stock}})</span>
					<button (click) = "masCerveza(beer)">+</button>
				<span *ngIf = "beer.stock > 0"><button (click) = "menosCerveza (beer)">-</button></span>
			</td>
			<td><input type="number" [(ngModel)] = "beer.stock"></td>
			</tr>
		</tbody>
	</table>`

**Comment by juliacosta98** [comment]
> <h3>Lista de cervezas</h3>
<table class="table table-dark">
		<thead>
			<tr>
			<th scope="col">{{titulos.name}}</th>
			<th scope="col">{{titulos.description}}</th>
			<th scope="col">{{titulos.price}}</th>
			<th scope="col">{{titulos.imagen}}</th>
			<th scope="col">{{titulos.stock}}</th>
			<th scope="col">{{titulos.carrito}}</th>
			</tr>
		</thead>
		<tbody>
			<tr *ngFor = "let beer of beers" [ngClass] = "{'oferta': beer.ofert, 'agotado': beer.stock <= 0}">
			<th scope="row">{{beer.name}}</th>
			<td>
					<ul>
						<li>{{titulos.alcohol}}: {{beer.alcohol}}</li>
						<li>{{titulos.ibu}}: {{beer.ibu}}</li>
						<li>{{titulos.color}}: {{beer.color}}</li>
						<li>{{titulos.og}}: {{beer.og}}</li>
						<li>{{titulos.amargor}}: {{beer.amargor}}</li>
					</ul>
				</td>
				<td>{{beer.price | currency}}</td>
				<td><img [src]=beer.imagen [alt]=beer.name width="30%"></td>
				<td><span *ngIf = "beer.stock <= 0"> Agotado </span>
					<span *ngIf = "beer.stock > 0"> Disponible ({{beer.stock}})</span>
					<button (click) = "masCerveza(beer)">+</button>
				<span *ngIf = "beer.stock > 0"><button (click) = "menosCerveza (beer)">-</button></span>
			</td>
			<td><input type="number" [(ngModel)] = "beer.stock"></td>
			</tr>
		</tbody>
	</table>

>

**Comment by juliacosta98** [comment]
![WhatsApp Image 2019-10-04 at 8 27 21 PM](https://user-images.githubusercontent.com/55962179/66245633-913b6980-e6e5-11e9-9a6f-e1419ec0dbb9.jpeg)

**Comment by juliacosta98** [comment]
Terminado el stiker de la tabla
