### ISSUE TITLE
Crear la tabla

### ISSUE THREAD

**Issue by lucasalmi** [lucasalmi/TPE-TIO#2]
Crear la tabla con condiciones en descripción.  @guidozoppo

**Comment by guidozoppo** [comment]
`<h3>Lista de cervezas</h3>
<table >
		<thead>
			<tr>
			<th>{{titulos.name}}</th>
			<th >{{titulos.description}}</th>
			<th >{{titulos.price}}</th>
			<th >{{titulos.imagen}}</th>
			<th >{{titulos.stock}}</th>
			<th >{{titulos.carrito}}</th>
			</tr>
		</thead>
		<tbody>
			<tr *ngFor = "let beer of beers" [ngClass] = "{'oferta': beer.ofert, 'agotado': beer.stock <= 0}">
			<th >{{beer.name}}</th>
			<td>
					<ul>
						<li>{{titulos.alcohol}}: {{beer.alcohol}}</li>
						<li>{{titulos.ibu}}: {{beer.ibu}}</li>
						<li>{{titulos.color}}: {{beer.color}}</li>
						<li>{{titulos.og}}: {{beer.og}}</li>
						<li>{{titulos.amargor}}: {{beer.amargor}}</li>
					</ul>
				</td>
				<td>{{beer.price | currency}}</td>
				<td><img [src]=beer.imagen [alt]=beer.name width="30%"></td>
				<td><span *ngIf = "beer.stock <= 0"> Agotado </span>
					<span *ngIf = "beer.stock > 0"> Disponible ({{beer.stock}})</span>
					<button (click) = "masCerveza(beer)">+</button>
				<span *ngIf = "beer.stock > 0"><button (click) = "menosCerveza (beer)">-</button></span>
			</td>
			<td><input type="number" [(ngModel)] = "beer.stock"></td>
			</tr>
		</tbody>
	</table>`
